version: '3'

services:
  db:
    container_name: "reserv-db"
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Sao_Paulo

  app:
    container_name: 'reserv-back-end'
    build: .
    command: npm run dev
    ports:
      - '80:80'
    volumes:
      - .:/src
    depends_on:
      - db
