version: '3'

services:
  db:
    container_name: "reserv-db"
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: jh556
      POSTGRES_USER: root
      POSTGRES_DB: appReservation
      TZ: America/Sao_Paulo

  app:
    container_name: 'reserv-back-end'
    build:
        dockerfile: Dockerfile
    command: npm run dev
    ports:
      - '80:80'
    volumes:
      - .:/src
    depends_on:
      - db
